name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 15 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked as stale because it has not had recent activity. It will be closed in 14 days if no further activity occurs.'
        stale-pr-message: 'This pull request has been marked as stale because it has not had recent activity. It will be closed in 14 days if no further activity occurs.'
        stale-pr-label: 'stale'
        days-before-stale: 180
        days-before-close: 14
        exempt-all-milestones: true
